// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks2.API.Data;

#nullable disable

namespace NZWalks2.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20250203174548_Seeding Data for difficulties and Regions")]
    partial class SeedingDatafordifficultiesandRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks2.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d76f8b-8c1d-460f-bee2-15f66a01b935"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("f58c0961-78ff-4409-98c1-78eebd6711af"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("6b2f0073-e323-4f68-a877-82df278f9d52"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks2.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef78a392-052f-4e97-8a91-749661fddfea"),
                            Code = "DTC",
                            Name = "DownTown cairo",
                            RegionImgUrl = "https://assets.nst.com.my/images/articles/cairo1_1554178412.jpg"
                        },
                        new
                        {
                            Id = new Guid("adcc7a33-c9af-4170-ae95-bdbe84997bed"),
                            Code = "MD",
                            Name = "Maadi",
                            RegionImgUrl = "https://i.pinimg.com/originals/5e/3e/52/5e3e523305335dcb1bbe62197aa9e992.jpg"
                        },
                        new
                        {
                            Id = new Guid("b9bd929c-ef15-4da9-8442-ff222663b976"),
                            Code = "ZM",
                            Name = "Zamalek",
                            RegionImgUrl = "https://2.bp.blogspot.com/-xsxTSZLgKag/UMGdtlTX5EI/AAAAAAAAACA/svGNjqTNEtQ/s1600/IMG_0629.JPG"
                        },
                        new
                        {
                            Id = new Guid("3dcff596-fc30-41b9-a41b-1f09be94609e"),
                            Code = "5TH",
                            Name = "Fifth Settlement",
                            RegionImgUrl = "https://realogy.co/images/upload/154046762.png"
                        },
                        new
                        {
                            Id = new Guid("c6877914-d178-4be0-9042-128d90ce58c1"),
                            Code = "TMG",
                            Name = "Madinaty",
                            RegionImgUrl = "https://th.bing.com/th/id/OIP.yf37VeOe1ka70Q5F0tLs-wHaEo?rs=1&pid=ImgDetMain"
                        });
                });

            modelBuilder.Entity("NZWalks2.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walk");
                });

            modelBuilder.Entity("NZWalks2.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks2.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks2.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
